import time
var = input("options: A=+  B=-  C=* D=/   :  ")
if var == 'A':
    var = input("First Number : ")
    sec_var = input("Second Number : ")
    x = int(var)
    y = int(sec_var)
    print("calculating")
    time.sleep(1)
    print("Your Number : ", x + y)
if var == 'B':
    var = input("First Number : ")
    sec_var = input("Second Number : ")
    x = int(var)
    y = int(sec_var)
    print("calculating")
    time.sleep(1)
    print("Your Number : ", x - y)
if var == 'C':
    var = input("First Number : ")
    sec_var = input("Second Number : ")
    x = int(var)
    y = int(sec_var)
    print("calculating")
    time.sleep(1)
    print("Your Number : ", x * y)
if var == 'D':
    var = input("First Number : ")
    sec_var = input("Second Number : ")
    x = int(var)
    y = int(sec_var)
    print("calculating")
    time.sleep(1)
    print("Your Number : ", x / y)
